#!/bin/bash

: ${slapd_basedn:=dc=ldap,dc=dit}
: ${slapd_admin_password:="$(pwgen -s1 32)"}

: ${slapd_require_ssl:=yes}
: ${slapd_ssl_ca_cert_file:=/etc/ssl/slapd/ca.crt}
: ${slapd_ssl_cert_file:=/etc/ssl/slapd/ldap.crt}
: ${slapd_ssl_key_file:=/etc/ssl/slapd/ldap.key}

: ${slapd_disable_anon:=yes}

# set secure umask
umask 0277

for var in slapd_ssl_ca_cert_file slapd_ssl_cert_file slapd_ssl_key_file; do
    file="$(eval "echo \"\$$var\"")"
    [ -L "$file" ] && file="$(readlink "$file")"
    dir="$(dirname "$file")"
    mkdir -m 0755 -p "$dir"
    eval "$var=\"$file\""
done

if ! [ -f "$slapd_ssl_cert_file" ]; then
    openssl req -newkey rsa:2048 -x509 -nodes -days 365 \
        -subj "/CN=$(hostname)" \
        -out "$slapd_ssl_cert_file" -keyout "$slapd_ssl_key_file"
    chmod 0444 "$slapd_ssl_cert_file"
    chown openldap:openldap "$slapd_ssl_cert_file" "$slapd_ssl_key_file"
fi

if ! [ -f "$slapd_ssl_ca_cert_file" ]; then
    ln -s "$slapd_ssl_cert_file" "$slapd_ssl_ca_cert_file"
fi

config_file=/etc/ldap/ldap.passwd
[ -L "$config_file" ] && config_file="$(readlink "$config_file")"
config_dir="$(dirname "$config_file")"
[ -d "$config_dir" ] || mkdir -m 0755 -p "$config_dir"
if [ -f "$config_file" ]; then
    slapd_admin_password="$(cat "$config_file")"
else
    echo -n "$slapd_admin_password" > "$config_file"
fi

# set normal umask
umask 0022

config_file=/etc/ldap/ldap.conf
[ -L "$config_file" ] && config_file="$(readlink "$config_file")"
config_dir="$(dirname "$config_file")"
[ -d "$config_dir" ] || mkdir -m 0755 -p "$config_dir"
[ -f "$config_file" ] || cat > "$config_file" <<EOF
URI ldapi:///
BASE $slapd_basedn
TLS_CACERT $slapd_ssl_ca_cert_file
SASL_MECH EXTERNAL
EOF

data_dir=/var/lib/ldap
[ -L "$data_dir" ] && data_dir="$(readlink "$data_dir")"
if ! [ -d "$data_dir" ]; then
    mkdir -m 0750 -p "$data_dir"
    chown openldap:openldap "$data_dir"
fi

config_dir=/etc/ldap/slapd.d
[ -L "$config_dir" ] && config_dir="$(readlink "$config_dir")"
[ -d "$config_dir" ] || mkdir -m 0755 -p "$config_dir"

[ -f "$config_dir/cn=config.ldif" ] && exit 0

cat /usr/share/slapd/slapd.init.ldif | \
    sed "s|@BACKEND@|mdb|g" | \
    sed "s|@BACKENDOBJECTCLASS@|olcMdbConfig|g" | \
    sed "s|@BACKENDOPTIONS@|olcDbMaxSize: 1073741824|g" | \
    sed "s|@SUFFIX@|$slapd_basedn|g" | \
    sed "s|@PASSWORD@|$(slappasswd -T /etc/ldap/ldap.passwd)|g" | \
    slapadd -b cn=config -F /etc/ldap/slapd.d
chown -LR openldap:openldap /etc/ldap/slapd.d

# start slapd on local socket and wait for it to come up
/usr/sbin/slapd -h ldapi:/// -g openldap -u openldap -F /etc/ldap/slapd.d
while ! ldapsearch -b cn=config >/dev/null 2>&1; do sleep 1; done

ldapmodify <<EOF
dn: cn=config
changetype: modify
replace: olcTLSCipherSuite
olcTLSCipherSuite: SECURE256:+SECURE128:-VERS-TLS-ALL:+VERS-TLS1.2:-RSA:-DHE-DSS:-CAMELLIA-128-CBC:-CAMELLIA-256-CBC
-
replace: olcTLSCACertificateFile
olcTLSCACertificateFile: $slapd_ssl_ca_cert_file
-
replace: olcTLSCertificateFile
olcTLSCertificateFile: $slapd_ssl_cert_file
-
replace: olcTLSCertificateKeyFile
olcTLSCertificateKeyFile: $slapd_ssl_key_file
EOF

[ "$slapd_require_ssl" = yes ] && ldapmodify <<EOF
dn: cn=config
changetype: modify
replace: olcLocalSSF
olcLocalSSF: 128
-
replace: olcSecurity
olcSecurity: ssf=128
EOF

[ "$slapd_disable_anon" = yes ] && ldapmodify <<EOF
dn: cn=config
changetype: modify
replace: olcDisallows
olcDisallows: bind_anon
-
replace: olcRequires
olcRequires: authc
EOF

export slapd_basedn slapd_admin_password
for file in $(find -L /etc/ldap/dbinit.d -type f -executable | sort); do
    $file
done

# make sure that slapd is not running
pidfile=/var/run/slapd/slapd.pid
while [ -f $pidfile ] && kill -INT $(cat $pidfile); do sleep 1; done
